### DISCUSSION TITLE
Deployment Option's replicas field

### DISCUSSION THREAD

**Discussion by yasirub** [Kong/gateway-operator-docs#31] [Q&A]
![image](https://github.com/Kong/gateway-operator-docs/assets/111842965/c169389f-79ba-40ae-b8f2-ea49112d43ca)

can we get more info about this issue mentioned in the kong-operator docs?

**Comment by pmalek** [comment]
Hi @yasirub 👋 

This basically says what's visible in the description. You can use this field simply by setting it in  `spec.deployment` like so:

```
apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: dataplane-example
spec:
  deployment:
    replicas: 3
    podTemplateSpec:
      spec:
        containers:
        - name: proxy
          image: kong:3.4
          env:
          - name: KONG_LOG_LEVEL
            value: debug
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 1
```

The issue captures a feature which is to implement this for `ControlPlane`s and for managed `Gateway`s.

Hope that helps.
